//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyOrganizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingPlan
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public bool Accepted { get; set; }
    }
}
