//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyOrganizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodayPlan
    {
        public int Id { get; set; }
        public string Task { get; set; }
        public bool IsRoutine { get; set; }
        public bool IsAdded { get; set; }
        public int UserId { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
