//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyOrganizer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionNum { get; set; }
        public int ToUserId { get; set; }
        public System.DateTime Date { get; set; }
        public double Sum { get; set; }
        public string Type { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
